### ISSUE TITLE
release latest artefacts on central

### ISSUE THREAD

**Issue by jangalinski** [smartics/smartics-jboss-modules-maven-plugin#24]
Its much more convenient than adding a repository for every vendor you work with.

**Comment by jamesnetherton** [comment]
+1 

I would find this really helpful right now, especially for the 2.1.0 release.

**Comment by jamesnetherton** [comment]
Currently getting "Service Temporarily Unavailable" from the smartics repo. Is there any chance that we can have a release to Maven central soon? 

I'd like to break the dependency on this repo from my builds.

**Comment by RobertReiner** [comment]
I'm sorry! The server should be up again.
I'll have a look at the process of registering the artifact with Maven Central now ...

**Comment by jamesnetherton** [comment]
Repo seems to be down again "Service Temporarily Unavailable".

**Comment by AntonKronseder** [comment]
The latest version 2.1.1 is now available at: https://repo1.maven.org/maven2/de/smartics/maven/plugin/smartics-jboss-modules-maven-plugin/2.1.1
