### ISSUE TITLE
"mvn package" fails without "mvn clean" first

### ISSUE THREAD

**Issue by rassie** [smartics/smartics-jboss-modules-maven-plugin#36]
The reason is [here](https://github.com/smartics/smartics-jboss-modules-maven-plugin/blob/4faf9a9202bf776d7fec3051f50d7c05d9eea912/src/main/java/de/smartics/maven/plugin/jboss/modules/domain/ModuleBuilder.java#L118): `File.mkdirs()` also returns `false` if a directory already exists.

**Comment by RobertReiner** [comment]
Thank you for the catch!

**Comment by rassie** [comment]
Thanks for the quick fix! Would this fix warrant a bug fix release? Asking for a friend :)

**Comment by RobertReiner** [comment]
How could I possible say 'no'? ;)

**Comment by rassie** [comment]
"Gimme a week" is always a possibility ;-) Thanks!

**Comment by RobertReiner** [comment]
My pleasure!
