### ISSUE TITLE
How to exlude provided dependencies?

### ISSUE THREAD

**Issue by nurzhsh** [smartics/smartics-jboss-modules-maven-plugin#45]
How to exlude provided dependencies?

**Comment by jamesnetherton** [comment]
You can use the [dependencyExcludes](https://www.smartics.eu/smartics-jboss-modules-maven-plugin/create-modules-archive-mojo.html#dependencyExcludes) configuration option. Or you can 'skip' modules and dependencies. There are some examples of this [here](https://github.com/smartics/smartics-jboss-modules-maven-plugin/tree/master/src/it/skip/src/etc/jboss-modules).
